name: Lockfile after version

on:
  push:
    branches: [changeset-release/master]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.2.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --lockfile-only

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
